from . import crop_rotate, nodes

NODE_CLASS_MAPPINGS = {**nodes.NODE_CLASS_MAPPINGS, **crop_rotate.NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**nodes.NODE_DISPLAY_NAME_MAPPINGS, **crop_rotate.NODE_DISPLAY_NAME_MAPPINGS}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
